## Written by Courtney Smith 7-4-2023
## Goal of script: Generate dendrogram and heatmap from (subsetted) haplotypes and heatmap of (non-subsetted) regression results

library(dplyr)
library(ggplot2)
library("dendextend")
library("RColorBrewer")
library("corrplot")
library(ComplexHeatmap)

# Set parameters
nsnps=c(1000)
blocks=1:3
pcut <- 1e-6
min_threshold=20000
ntraits=1
zcut = 4
extended = "N"

for (nsnp in nsnps){
  for (bnum in blocks){
    #### SUBSET DOWN TO CLUSTERS AND TRAITS TO FOCUS ON
    # set directories
    hla_dir="/home/ivm/haplo_analysis/"
    nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
    setwd(nsnp_dir)

    # load data
    c <- data.table::fread(paste0("hb",bnum,"_clusterstats.txt")) # cluster info, generated by hapclusterandplot.R
    m <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_mungedgenotypes01.txt")) # load in genptyoe info, generated by hapclusterandplot.R
    h1 <- data.table::fread(paste0("hb",bnum,"_regresults.txt")) %>% rename(trait=nimi)

    ## Get stats
    # how many unique haplotypes total
    length(unique(m$hap))

    # how many traits have at least one cluster w/ p < pcut of all clusters
    length(unique(filter(h1,p<pcut)$trait)) # (of the 269 tested)

    ## Calculate z-scores and add in dropped cluster
    h <- h1 %>% mutate(z=beta/se)
    beta <- tidyr::spread(h %>% select(trait,cluster,beta),cluster,beta)
    z <- tidyr::spread(h %>% select(trait,cluster,z),cluster,z)
    traits <- z$trait
    rownames(z) <- traits
    z <- z %>% select(-trait)
    # add in dropped cluster w/ rescale
    z <- z %>% mutate(dropped=0)
    # Function to rescale row values to have mean 0
    rescale_mean_zero <- function(row) {
      mean_zero <- row - mean(row)
      return(mean_zero)
    }
    # Apply the rescaling function to each row of the dataframe
    z_full <- t(apply(z, 1, rescale_mean_zero))
    rownames(z_full) <- traits

    # identify dropped cluster and rename last column added (dropped column) with it
    dropped <- filter(c,cluster_total==max(c$cluster_total))$Cluster
    numcol <- ncol(z_full)
    colnames(z_full) <- c(head(colnames(z_full),numcol-1),dropped)
    droppedextra <- setdiff(c$Cluster,colnames(z_full))

    # filter to a small number of traits of interest (have >= 1 clusters w/ abs(z)>zcut in the clusters to plot)
    z_filt <- z_full[(rowSums(abs(z_full)>zcut))>0,]

    # filter to a subset of clusters that have total doses > min_cutoff or at least 1 trait with abs(z)>zcut
    mckeep <- (c %>% filter(cluster_total>min_threshold))$Cluster
    mckeep <- mckeep[!mckeep %in% droppedextra]
    clustkeep <- unique(c(mckeep,colnames(z_full[,(colSums(abs(z_full)>zcut))>0])))
    z_filt <- as.data.frame(z_filt) %>% select(all_of(clustkeep))

    # stats
    dim(z_filt) # rows is traits, columns is clusters

    # save these results
    data.table::fwrite(z_filt, paste0(nsnp_dir,"hb",bnum,"_regdatatoplot.txt"), row.names = T, quote = F, sep = "\t")
    z_full_save <- as.data.frame(z_full)
    colnames(z_full_save) <- paste0("hapgroup",colnames(z_full))
    data.table::fwrite(z_full_save, paste0(nsnp_dir,"hb",bnum,"_regdatafull.txt"), row.names = T, quote = F, sep = "\t")

    # Switch to long form and annotate which traits and hap groups are included in fig 5
    plottraits <- rownames(z_filt) # list of traits included in fig 5
    plothapgroups <- colnames(z_filt) # list of hap groups included in fig 5
    z_full_long <- as.data.frame(z_full)
    z_full_long$traits <- rownames(z_full_long)
    z_full_long <- reshape2::melt(z_full_long) %>%
      rename(hapgroup=variable,Z_rescaled=value) %>% mutate(plotted=ifelse((traits %in% plottraits) & (hapgroup %in% plothapgroups),"yes","no"))
    data.table::fwrite(z_full_long, paste0(nsnp_dir,"hb",bnum,"_regdatafull_long.txt"), row.names = T, quote = F, sep = "\t")

    ### Add color assignments
    # Step 1: Generate colors
    colors = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
    # Step 2: Convert to RGB
    rgb_values = col2rgb(colors)
    # Step 3: Calculate brightness
    brightness = 0.299*rgb_values[1,] + 0.587*rgb_values[2,] + 0.114*rgb_values[3,]
    # Step 4: Filter colors
    threshold = 150
    col_vector = colors[brightness < threshold]
    #col_vector = c("dodgerblue2", "#E31A1C", "green4","#6A3D9A", "#FF7F00","black", "gold1", "skyblue2", "#FB9A99", "palegreen2",  "#CAB2D6", "#FDBF6F", "gray70", "khaki2",  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",  "darkturquoise", "green1", "yellow4", "yellow3","darkorange4", "brown")
    colors <- data.frame(cluster=colnames(z_filt),
                         color= sample(col_vector,size=ncol(z_filt)))

    #### MAKE THE SUBSETDOWN DENDROGRAM AND SNP HEATMAP
    # select the n most common haplotypes from each cluster, only clusters to keep
    nkeep=40
    subset_df <- m %>% group_by(final_cluster) %>% arrange(-total) %>% slice(1:nkeep)
    subset_df <- subset_df %>% filter(final_cluster %in% clustkeep)
    df <- t(as.matrix(subset_df %>% ungroup %>% select(matches("chr6"))))
    l<- as.character(subset_df$final_cluster)
    C <- cluster_within_group(df,l)
    set.seed(123)
    tiff(paste0(fdir,"snps",nsnp,"/figures_askout07012024/",nsnp,"_b",bnum,"minthres_",min_threshold,"_traits",ntraits,"_dendro.tiff"),height=10,width=10,res=300,units="in")
    Heatmap(t(df), cluster_rows = C, border=TRUE, row_split = length(unique(subset_df$final_cluster)),
            show_column_dend = FALSE,
            cluster_columns = FALSE,show_column_names=FALSE,
            show_row_names = TRUE,
            col=c("black","white"),show_heatmap_legend = FALSE,
            row_gap=unit(0.8,"mm"),
            row_title_gp = gpar(fontsize = 25),
            row_title_rot = 0)#,left_annotation = rowAnnotation(Cluster = l,show_legend=F))
    dev.off()
    clustorder <- unique(l[order.dendrogram(C)]) # top to bottom

    #### PLOT THE REGRESSION RESULTS HEATMAP
    # Set parameters
    fdir="/home/ivm/haplo_analysis/figures/"

    # Reorder and name the clusters and subset down just to those to plot
    z <- z_filt
    #colnames(z) <- paste0("Cluster ",colnames(z))
    #clusternames <- unique(gsub(":.*","",sorted_order)) # sorted_order from the making of the subsetted dendrogram / snp 0s/1s heatmap
    #clusternames <- paste0("Cluster ",rev(clustorder))
    clusternames <- rev(clustorder)
    z <- as.data.frame(z) %>% select(clusternames) # reorder columns
    z_notcut <- z

    # Add cutoff values for plotting
    z[z<(-5)] <- -5
    z[z>(5)] <- 5

    # Cluster the traits axis of the heatmap (keep clusters in order of dendrogram not clustered here
    hc <- hclust(dist(z,method="euclidean"),method="ward.D")
    z <- z[hc$order,]
    z$traits <- rownames(z)
    z$traits <- factor(z$traits,levels=traits)
    melted_df <- reshape2::melt(z)

    # Add in updated trait names
    tn <- data.table::fread("/home/ivm/from_satu/general_files/new_plot_names.txt",header=T) %>%
      select(trait,Plot)

    melted_df <-melted_df %>% left_join(tn,by=c("traits"="trait"))

    # Plot the heatmap using ggplot2
    ggplot(melted_df, aes(x = Plot, y = variable, fill = value)) + # x=traits
      #geom_tile(color="black",size=1)+
      geom_tile()+
      #scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0)+
      scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0, limits = c(-5, 5))+
      theme_classic()+
      theme(text = element_text(size=25),
            axis.text.x = element_text(angle = -70, hjust = 0))+
      #labs(x="Traits",y="Clusters",fill="Z-score")
      labs(x="",y="",fill="Z-score")+
      scale_x_discrete(limits=unique(melted_df$Plot)) # z$traits
    ggsave(paste0(fdir,"snps",nsnp,"/figures_askout07012024/",nsnp,"_b",bnum,"minthres_",min_threshold,"_traits",ntraits,"_cutoff5.tiff"),height=10,width=20)
    #ggsave(paste0(fdir,"snps",nsnp,"/",nsnp,"_b",bnum,"minthres_",min_threshold,"_traits",ntraits,"_cutoff5.png"),height=10,width=20)
    #ggsave(paste0(fdir,"snps",nsnp,"/figures_askout07012024/",nsnp,"_b",bnum,"minthres_",min_threshold,"_traits",ntraits,"_cutoff5.pdf"),height=10,width=10,units="in")
    #ggsave(paste0(fdir,"snps",nsnp,"/figures_askout07012024/",nsnp,"_b",bnum,"minthres_",min_threshold,"_traits",ntraits,"_cutoff5.pdf"))

    data.table::fwrite(melted_df %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted.txt"), row.names = F, quote = F, sep = ",")
    melted_df_plotted <- melted_df

    # repeat the same as above but without abs(Z)>5 cutoff
    # Cluster the traits axis of the heatmap (keep clusters in order of dendrogram not clustered here
    hc <- hclust(dist(z_notcut,method="euclidean"),method="ward.D")
    z_notcut <- z_notcut[hc$order,]
    z_notcut$traits <- rownames(z_notcut)
    z_notcut$traits <- factor(z_notcut$traits,levels=traits)
    melted_df <- reshape2::melt(z_notcut)
    # Add in updated trait names
    tn <- data.table::fread("/home/ivm/from_satu/general_files/new_plot_names.txt",header=T) %>%
      select(trait,Plot)
    melted_df <-melted_df %>% left_join(tn,by=c("traits"="trait"))
    data.table::fwrite(melted_df %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted_notcutoff.txt"), row.names = F, quote = F, sep = ",")

    cn <- data.frame(cluster=clusternames)
    data.table::fwrite(cn,paste0(nsnp_dir,"hb",bnum,"_heatmapclustorder.txt"), row.names = F, quote = F, sep = ",")
    if (extended=="N"){next}

    ### Same thing but for all clusters for all traits
    # Add cutoff values for plotting
    z <- z_full
    z[z<(-5)] <- -5
    z[z>(5)] <- 5

    # Cluster the traits axis of the heatmap (keep clusters in order of dendrogram not clustered here
    hc <- hclust(dist(z,method="euclidean"),method="ward.D")
    z <- z[hc$order,]
    melted_df_full <- reshape2::melt(z)
    ggplot(melted_df_full, aes(x = Var1, y = Var2, fill = value)) +
      #geom_tile(color="black",size=1)+
      geom_tile()+
      #scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0)+
      scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0, limits = c(-5, 5))+
      theme_classic()+
      theme(axis.text.x = element_text(angle = 70, hjust = 1))+
      #labs(x="Traits",y="Clusters",fill="Z-score")
      labs(x="",y="",fill="Z-score")
    data.table::fwrite(melted_df_full %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted_full.txt"), row.names = F, quote = F, sep = ",")

    # repeat above but without cutoff
    z <- z_full
    hc <- hclust(dist(z,method="euclidean"),method="ward.D")
    z <- z[hc$order,]
    melted_df_full <- reshape2::melt(z)
    data.table::fwrite(melted_df_full %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted_full_notcutoff.txt"), row.names = F, quote = F, sep = ",")

    ### Same thing but for custom subset of traits (but still haplotype groups from subset plotted)
    custom_traits=c("K11_IBD_STRICT","K11_IBD_STRICT_PSC")
    plot_clusters=unique(melted_df$variable)
    ggplot(melted_df_full %>% filter(Var1 %in%custom_traits & Var2 %in% plot_clusters), aes(x = Var1, y = factor(Var2), fill = value)) +
      #geom_tile(color="black",size=1)+
      geom_tile(width=0.1)+
      #scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0)+
      scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0, limits = c(-5, 5))+
      theme_classic()+
      theme(axis.text.x = element_text(angle = 70, hjust = 1))+
      #labs(x="Traits",y="Clusters",fill="Z-score")
      labs(x="",y="",fill="Z-score")

  }
}

### Going through stats
c <-  data.table::fread(paste0("hb",bnum,"_clusterstats.txt")) #%>% select(-Merged_Haplotype)
h <- data.table::fread(paste0("hb",bnum,"_haplostats.txt"))
c <- c %>% mutate(frac_twodose=cluster_twodose/cluster_unippl)
length(unique(m$hap)) # total number unqiue hap
dim(c) # number cluster total
dim(h %>% group_by(Cluster) %>% count() %>% filter(n>100))
dim(h %>% group_by(Cluster) %>% count() %>% filter(n>1000))
max(((h %>% group_by(Cluster) %>% count()))$n) # max num haplotypes in cluster
summary(c %>% select(cluster_total))
nrow((c %>% filter(cluster_total>10000))) # number clusters with > n total doses
nrow((c %>% filter(cluster_total>20000))) # number clusters with > n total doses
dim(z_filt) # traits by clusters plotted

# starting with melted_df used to generate that block's part of fig 5
length(unique(melted_df_plotted$variable))
filter(c,Cluster %in% unique(melted_df_plotted$variable))$cluster_total
filter(c,Cluster %in% unique(melted_df_plotted$variable) & cluster_total < 5000)$cluster_total
min(filter(c,Cluster %in% unique(melted_df_plotted$variable))$cluster_total)
quantile(filter(c,Cluster %in% unique(melted_df_plotted$variable))$cluster_total)

############ SAVE SUPPLEMENTARY TABLES 3
library(dplyr)
nsnp=1000
hla_dir="/home/ivm/haplo_analysis/"
nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
setwd(nsnp_dir)

c1 <-  data.table::fread(paste0("hb",1,"_clusterstats.txt")) #%>% select(-Merged_Haplotype)
c2 <-  data.table::fread(paste0("hb",2,"_clusterstats.txt")) #%>% select(-Merged_Haplotype)
c3 <-  data.table::fread(paste0("hb",3,"_clusterstats.txt")) #%>% select(-Merged_Haplotype)
c <- bind_rows(c1 %>% mutate(block=1),c2 %>% mutate(block=2),c3 %>% mutate(block=3))
c <- c %>% mutate(frac_twodose=cluster_twodose/cluster_unippl)
c <- c %>% rename(haplotype_group=Cluster,num_onedose=cluster_onedose,
                  num_twodose=cluster_twodose,num_uniquepeople=cluster_unippl,
                  total_doses=cluster_total)

# For any dose value with <10 then recorded <10 instead of the number
#c$num_twodose <- ifelse(c$num_twodose<10,"<10",c$num_twodose)
#c$num_onedose <- ifelse(c$num_onedose<10,"<10",c$num_onedose)
#c$total_doses <- ifelse(c$total_doses<10,"<10",c$total_doses)
data.table::fwrite(c, paste0(nsnp_dir,"allhaplotype_group_stats_full.txt"), row.names = F, quote = F, sep = "\t")
data.table::fwrite(c %>% select(-num_onedose,-num_twodose,-num_uniquepeople,-frac_twodose), paste0(nsnp_dir,"allhaplotype_group_stats.txt"), row.names = F, quote = F, sep = "\t")

#BLOCK 1
h <- data.table::fread(paste0("hb",1,"_haplostats.txt"))
#h <- bind_rows(h1 %>% mutate(block=1),h2 %>% mutate(block=2),h3 %>% mutate(block=3))
h <- h %>% mutate(frac_twodose=twodose/unippl)
h <- h %>% select(-dendroname,-color) %>% rename(haplotype_group=Cluster,
                                                 num_onedose=onedose,
                                                 num_twodose=twodose,
                                                 num_uniquepeople=unippl,
                                                 total_doses=total)
data.table::fwrite(h, paste0(nsnp_dir,"allhaplotype_stats_b1.txt"), row.names = F, quote = F, sep = "\t")
data.table::fwrite(h %>% filter(total_doses>10)%>% select(-num_onedose,-num_twodose,-num_uniquepeople,-frac_twodose), paste0(nsnp_dir,"allhaplotype_stats_b1_morethan10.txt"), row.names = F, quote = F, sep = "\t")
# nrow(h %>% filter(total_doses>10&num_uniquepeople>10&num_onedose>10&num_twodose<1))

#BLOCK 2
h <- data.table::fread(paste0("hb",2,"_haplostats.txt"))
h <- h %>% mutate(frac_twodose=twodose/unippl)
h <- h %>% select(-dendroname,-color) %>% rename(haplotype_group=Cluster,
                                                 num_onedose=onedose,
                                                 num_twodose=twodose,
                                                 num_uniquepeople=unippl,
                                                 total_doses=total)
data.table::fwrite(h, paste0(nsnp_dir,"allhaplotype_stats_b2.txt"), row.names = F, quote = F, sep = "\t")
data.table::fwrite(h %>% filter(total_doses>10)%>% select(-num_onedose,-num_twodose,-num_uniquepeople,-frac_twodose), paste0(nsnp_dir,"allhaplotype_stats_b2_morethan10.txt"), row.names = F, quote = F, sep = "\t")

#Block 3
h <- data.table::fread(paste0("hb",3,"_haplostats.txt"))
h <- h %>% mutate(frac_twodose=twodose/unippl)
h <- h %>% select(-dendroname,-color) %>% rename(haplotype_group=Cluster,
                                                 num_onedose=onedose,
                                                 num_twodose=twodose,
                                                 num_uniquepeople=unippl,
                                                 total_doses=total)
data.table::fwrite(h, paste0(nsnp_dir,"allhaplotype_stats_b3.txt"), row.names = F, quote = F, sep = "\t")
data.table::fwrite(h %>% filter(total_doses>10) %>% filter(total_doses>10)%>% select(-num_onedose,-num_twodose,-num_uniquepeople,-frac_twodose), paste0(nsnp_dir,"allhaplotype_stats_b3_morethan10.txt"), row.names = F, quote = F, sep = "\t")
