
## Written by Courtney Smith 9-20-2024
## Goal of script: Generate dendrogram and heatmap from (subsetted) haplotypes and heatmap of (non-subsetted) regression results
# Repeat this with remaining sets of randomly selected 1000 snps (bilallelic, MAF>1%); takes outputs of hapclusterandregress_check6to14.R

library(dplyr)
library(ggplot2)
library("dendextend")
library("RColorBrewer")
library("corrplot")
library(ComplexHeatmap)

# Set parameters
blocks=1:3
checks=2:14
pcut <- 1e-6
min_threshold=20000
ntraits=1
zcut = 4
extended = "N"
nsnp=1000

# If want run manually
checknum=6 # c(6,14)
bnum=1

for (checknum in checks){
  for (bnum in blocks){
    #### SUBSET DOWN TO CLUSTERS AND TRAITS TO FOCUS ON
    # set directories
    hla_dir=paste0("/home/ivm/haplo_analysis/check",checknum,"/")
    nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
    setwd(nsnp_dir)

    # load data
    c <- data.table::fread(paste0("hb",bnum,"_clusterstats.txt")) # cluster info, generated by hapclusterandplot.R
    h1 <- data.table::fread(paste0("hb",bnum,"_regresults.txt")) %>% rename(trait=nimi)

    ## Get stats
    # how many traits have at least one cluster w/ p < pcut of all clusters
    length(unique(filter(h1,p<pcut)$trait)) # (of the 269 tested)

    ## Calculate z-scores and add in dropped cluster
    h <- h1 %>% mutate(z=beta/se)
    beta <- tidyr::spread(h %>% select(trait,cluster,beta),cluster,beta)
    z <- tidyr::spread(h %>% select(trait,cluster,z),cluster,z)
    traits <- z$trait
    rownames(z) <- traits
    z <- z %>% select(-trait)
    # add in dropped cluster w/ rescale
    z <- z %>% mutate(dropped=0)
    # Function to rescale row values to have mean 0
    rescale_mean_zero <- function(row) {
      mean_zero <- row - mean(row)
      return(mean_zero)
    }
    # Apply the rescaling function to each row of the dataframe
    z_full <- t(apply(z, 1, rescale_mean_zero))
    rownames(z_full) <- traits

    # identify dropped cluster and rename last column added (dropped column) with it
    dropped <- filter(c,cluster_total==max(c$cluster_total))$Cluster
    numcol <- ncol(z_full)
    colnames(z_full) <- c(head(colnames(z_full),numcol-1),dropped)
    droppedextra <- setdiff(c$Cluster,colnames(z_full))

    # filter to a small number of traits of interest (have >= 1 clusters w/ abs(z)>zcut in the clusters to plot)
    z_filt <- z_full[(rowSums(abs(z_full)>zcut))>0,]

    # filter to a subset of clusters that have total doses > min_cutoff or at least 1 trait with abs(z)>zcut
    mckeep <- (c %>% filter(cluster_total>min_threshold))$Cluster
    mckeep <- mckeep[!mckeep %in% droppedextra]
    clustkeep <- unique(c(mckeep,colnames(z_full[,(colSums(abs(z_full)>zcut))>0])))
    z_filt <- as.data.frame(z_filt) %>% select(all_of(clustkeep))

    # stats
    dim(z_filt) # rows is traits, columns is clusters

    # save these results
    data.table::fwrite(z_filt, paste0(nsnp_dir,"hb",bnum,"_regdatatoplot.txt"), row.names = T, quote = F, sep = "\t")
    z_full_save <- as.data.frame(z_full)
    colnames(z_full_save) <- paste0("hapgroup",colnames(z_full))
    data.table::fwrite(z_full_save, paste0(nsnp_dir,"hb",bnum,"_regdatafull.txt"), row.names = T, quote = F, sep = "\t")

    #### PLOT THE REGRESSION RESULTS HEATMAP
    # Set parameters
    fdir=paste0("/home/ivm/haplo_analysis/check",checknum,"/figures/")

    # Reorder and name the clusters and subset down just to those to plot
    z <- z_filt
    z_notcut <- z

    # Add cutoff values for plotting
    z[z<(-5)] <- -5
    z[z>(5)] <- 5

    # Cluster the traits axis of the heatmap (keep clusters in order of dendrogram not clustered here
    hc <- hclust(dist(z,method="euclidean"),method="ward.D")
    z <- z[hc$order,]
    z$traits <- rownames(z)
    z$traits <- factor(z$traits,levels=traits)
    melted_df <- reshape2::melt(z)

    # Add in updated trait names
    tn <- data.table::fread("/home/ivm/from_satu/general_files/new_plot_names.txt",header=T) %>%
      select(trait,Plot)

    melted_df <-melted_df %>% left_join(tn,by=c("traits"="trait"))

    # Plot the heatmap using ggplot2
    ggplot(melted_df, aes(x = Plot, y = variable, fill = value)) + # x=traits
      #geom_tile(color="black",size=1)+
      geom_tile()+
      #scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0)+
      scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0, limits = c(-5, 5))+
      theme_classic()+
      theme(text = element_text(size=20),
            axis.text.x = element_text(angle = -70, hjust = 0))+
      #labs(x="Traits",y="Clusters",fill="Z-score")
      labs(x="",y="",fill="Z-score")+
      scale_x_discrete(limits=unique(melted_df$Plot)) # z$traits
    ggsave(paste0(fdir,nsnp,"_b",bnum,"minthres_",min_threshold,"_traits",ntraits,"_cutoff5.tiff"),height=15,width=20)
    data.table::fwrite(melted_df %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted.txt"), row.names = F, quote = F, sep = ",")
    ### Same thing but for all clusters for all traits
    # Add cutoff values for plotting
    z <- z_full
    z[z<(-5)] <- -5
    z[z>(5)] <- 5

    # Cluster the traits axis of the heatmap (keep clusters in order of dendrogram not clustered here
    hc <- hclust(dist(z,method="euclidean"),method="ward.D")
    z <- z[hc$order,]
    melted_df_full <- reshape2::melt(z)
    ggplot(melted_df_full, aes(x = Var1, y = Var2, fill = value)) +
      #geom_tile(color="black",size=1)+
      geom_tile()+
      #scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0)+
      scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0, limits = c(-5, 5))+
      theme_classic()+
      theme(axis.text.x = element_text(angle = 70, hjust = 1))+
      #labs(x="Traits",y="Clusters",fill="Z-score")
      labs(x="",y="",fill="Z-score")
    #data.table::fwrite(melted_df_full %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted_full.txt"), row.names = F, quote = F, sep = ",")

    # repeat above but without cutoff
    z <- z_full
    hc <- hclust(dist(z,method="euclidean"),method="ward.D")
    z <- z[hc$order,]
    melted_df_full <- reshape2::melt(z)
    #data.table::fwrite(melted_df_full %>% rename(hapgroup=variable,Z_rescaled=value),paste0(nsnp_dir,"hb",bnum,"_heatmapplotted_full_notcutoff.txt"), row.names = F, quote = F, sep = ",")

  }
}

############## Compare check results with original
hla_dir=paste0("/home/ivm/haplo_analysis/")
nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
z_full_og <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_regdatafull.txt"),header=T) # full results
z_full_og_l <- reshape2::melt(z_full_og) # full results in long form
z_og <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_heatmapplotted.txt")) # just results included in fig 5
length(unique(z_og$traits))

z_full_all <- list()
z_full_all_filt <- list()

for (bnum in blocks){
  for (checknum in checks){
    hla_dir=paste0("/home/ivm/haplo_analysis/check",checknum,"/")
    nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
    z_full_save <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_regdatafull.txt"),header=T)
    z_full_save_l <- reshape2::melt(z_full_save)
    z_check <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_heatmapplotted.txt")) # just results included in fig 5
    print(paste0("Numbers below are total unique traits and overlap with OG for block ",bnum," and check ",checknum))
    print(length(unique(z_check$traits)))
    print(length(intersect(unique(z_check$traits),unique(z_og$traits))))
    checkbnum = paste0("block",bnum,"-check",checknum)
    z_full_all[[checkbnum]] <- z_full_save_l %>% mutate(check=checknum,block=bnum,checkbnum=checkbnum,checkhap=paste0("check",checknum,"-",variable))

    # filter to just the relevant haplotypes for this block
    keephaps <- paste0("hapgroup",unique(z_check$hapgroup))
    z_full_save_l_filt <- z_full_save_l %>% filter(variable %in% keephaps)
    z_full_all_filt[[checkbnum]] <- z_full_save_l_filt %>% mutate(check=checknum,block=bnum,checkbnum=checkbnum,checkhap=paste0("check",checknum,"-",variable))

  }
}

z_full_comb <- bind_rows(z_full_all)
z_full_comb_filt <- bind_rows(z_full_all_filt)

hla_dir=paste0("/home/ivm/haplo_analysis/")
nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
data.table::fwrite(z_full_comb,paste0(nsnp_dir,"hb",bnum,"_combinedhapregress_checks.txt"), row.names = F, quote = F, sep = ",")
data.table::fwrite(z_full_comb_filt,paste0(nsnp_dir,"hb",bnum,"_combinedhapregress_checks_filt.txt"), row.names = F, quote = F, sep = ",")

#######################
# Make mega heatmap for check's relevant haplotypes for the original block's relevant traits
bnum=3
hla_dir=paste0("/home/ivm/haplo_analysis/")
nsnp_dir=nsnp_dir=paste0(hla_dir,"snps",nsnp,"/")
z_full_og <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_regdatafull.txt"),header=T) # full results
z_full_og_l <- reshape2::melt(z_full_og) # full results in long form
z_og <- data.table::fread(paste0(nsnp_dir,"hb",bnum,"_heatmapplotted.txt")) # just results included in fig 5
og_traits <- unique(z_og$traits)
z_cf <- filter(z_full_comb_filt,V1 %in% og_traits & block == bnum)
z_cf <- z_cf %>% left_join(z_og %>% select(traits,Plot) %>% distinct(),by=c("V1"="traits"))

# cap at -5 to 5
z_cf$value <- as.numeric(ifelse(z_cf$value > 5, 5, ifelse(z_cf$value < -5, -5, z_cf$value)))

# cluster y axis
z_cf$uniqueid <- paste0(z_cf$V1,"-",z_cf$checkhap)
z_cf$checkhap <- as.factor(z_cf$checkhap)
df_wide <- as.data.frame(z_cf) %>%select(checkhap,value,Plot)%>% tidyr::pivot_wider(names_from=Plot,values_from=value)
row.names(df_wide) <- df_wide$checkhap
df_wide_clust <- df_wide %>% select(-checkhap) %>% as.matrix()
hclust_results <- hclust(dist(df_wide_clust))
z_cf$checkhap <- factor(z_cf$checkhap, levels = row.names(df_wide)[hclust_results$order])

#df_wide <- as.data.frame(z_cf) %>%select(checkhap,value,Plot)%>% tidyr::pivot_wider(names_from=checkhap,values_from=value)
#row.names(df_wide) <- df_wide$Plot
#df_wide_clust <- df_wide %>% select(-Plot) %>% as.matrix()
#hclust_results <- hclust(dist(df_wide_clust))
#z_cf$Plot <- factor(z_cf$Plot, levels = row.names(df_wide)[hclust_results$order])

ggplot(z_cf, aes(x = Plot, y = checkhap, fill = value)) + # x=traits
  geom_tile()+
  scale_fill_gradient2(low="blue",mid="white",high="red",midpoint=0, limits = c(-5, 5))+
  theme_classic()+
  theme(text = element_text(size=20),
        axis.text.x = element_text(angle = -70, hjust = 0))+
  labs(x="",y="",fill="Z-score")+
  scale_x_discrete(limits=unique(z_og$Plot)) # z$traits
ggsave(paste0("/home/ivm/haplo_analysis/figures/snps1000/combinedchecks_bnum",bnum,"_zcut5.png"),height=15,width=20)
